// ======================================================
// Created by ssumeshc 0.2
// Date of conversion : Wed Apr 06 18:42:19 2011

// Input file: ..\..\..\Meshes\SSU\VAB_exterior_1980.msh
// ======================================================

#pragma once

const unsigned int NUMGRP = 159;

const unsigned int GRP_SOUTHWINDOW	=	0;	//south_window
const unsigned int GRP_GROUP_147	=	1;	//Group 147
const unsigned int GRP_BOX	=	2;	//box
const unsigned int GRP_BOXA	=	3;	//box
const unsigned int GRP_BOXB	=	4;	//box
const unsigned int GRP_GROUP_166	=	5;	//Group 166
const unsigned int GRP_VABFLOOR	=	6;	//VAB_floor
const unsigned int GRP_MESH	=	7;	//mesh
const unsigned int GRP_A	=	8;	//A
const unsigned int GRP_AA	=	9;	//A
const unsigned int GRP_R	=	10;	//R
const unsigned int GRP_GROUP_1_STATIC	=	11;	//Group 1 STATIC
const unsigned int GRP_NORTHENTRANCETAIL1	=	12;	//North_entrance_tail1
const unsigned int GRP_BOXC	=	13;	//box
const unsigned int GRP_HB3HORIZONTALDOORR2	=	14;	//HB3_Horizontal_door_R2
const unsigned int GRP_BLOCK	=	15;	//block
const unsigned int GRP_HB3VLD1	=	16;	//HB3_VLD1
const unsigned int GRP_HB3VLD2	=	17;	//HB3_VLD2
const unsigned int GRP_HB1VLD1	=	18;	//HB1_VLD1
const unsigned int GRP_HB1VLD5	=	19;	//HB1_VLD5
const unsigned int GRP_HB1VLD6	=	20;	//HB1_VLD6
const unsigned int GRP_HB1VLD7	=	21;	//HB1_VLD7
const unsigned int GRP_HB1HORIZONTALDOORL1	=	22;	//HB1_Horizontal_door_L1
const unsigned int GRP_HB1HORIZONTALDOORR1	=	23;	//HB1_Horizontal_door_R1
const unsigned int GRP_HB1HORIZONTALDOORL2	=	24;	//HB1_Horizontal_door_L2
const unsigned int GRP_HB1HORIZONTALDOORR2	=	25;	//HB1_Horizontal_door_R2
const unsigned int GRP_HB1VLD2	=	26;	//HB1_VLD2
const unsigned int GRP_HB1VLD4	=	27;	//HB1_VLD4
const unsigned int GRP_HB1VLD3	=	28;	//HB1_VLD3
const unsigned int GRP_VABFLOORA	=	29;	//VAB_floor
const unsigned int GRP_BLOCKA	=	30;	//block
const unsigned int GRP_BLOCKB	=	31;	//block
const unsigned int GRP_BLOCKC	=	32;	//block
const unsigned int GRP_DOORBOX	=	33;	//doorbox
const unsigned int GRP_BLOCKD	=	34;	//block
const unsigned int GRP_XFERAISLECRANERAIL	=	35;	//Xfer_aisle_crane_rail
const unsigned int GRP_BLOCKE	=	36;	//block
const unsigned int GRP_BLOCKF	=	37;	//block
const unsigned int GRP_HB3VLD7	=	38;	//HB3_VLD7
const unsigned int GRP_HB3VLD6	=	39;	//HB3_VLD6
const unsigned int GRP_HB3VLD5	=	40;	//HB3_VLD5
const unsigned int GRP_HB3VLD4	=	41;	//HB3_VLD4
const unsigned int GRP_HB3VLD3	=	42;	//HB3_VLD3
const unsigned int GRP_DOORBOXA	=	43;	//doorbox
const unsigned int GRP_BLOCKG	=	44;	//block
const unsigned int GRP_BLOCKH	=	45;	//block
const unsigned int GRP_BLOCKI	=	46;	//block
const unsigned int GRP_GROUP_146	=	47;	//Group 146
const unsigned int GRP_HB3HORIZONTALDOORL1	=	48;	//HB3_Horizontal_door_L1
const unsigned int GRP_HB3HORIZONTALDOORR1	=	49;	//HB3_Horizontal_door_R1
const unsigned int GRP_HB3HORIZONTALDOORL2	=	50;	//HB3_Horizontal_door_L2
const unsigned int GRP_HB2HORIZONTALDOORL2	=	51;	//HB2_Horizontal_door_L2
const unsigned int GRP_HB2HORIZONTALDOORR2	=	52;	//HB2_Horizontal_door_R2
const unsigned int GRP_HB2HORIZONTALDOORR1	=	53;	//HB2_Horizontal_door_R1
const unsigned int GRP_HB2HORIZONTALDOORL1	=	54;	//HB2_Horizontal_door_L1
const unsigned int GRP_HB2VLD3	=	55;	//HB2_VLD3
const unsigned int GRP_HB2VLD4	=	56;	//HB2_VLD4
const unsigned int GRP_HB2VLD5	=	57;	//HB2_VLD5
const unsigned int GRP_HB2VLD6	=	58;	//HB2_VLD6
const unsigned int GRP_HB2VLD7	=	59;	//HB2_VLD7
const unsigned int GRP_HB4VLD2	=	60;	//HB4_VLD2
const unsigned int GRP_HB4VLD3	=	61;	//HB4_VLD3
const unsigned int GRP_HB4VLD4	=	62;	//HB4_VLD4
const unsigned int GRP_HB4HORIZONTALDOORR2	=	63;	//HB4_Horizontal_door_R2
const unsigned int GRP_HB4HORIZONTALDOORL2	=	64;	//HB4_Horizontal_door_L2
const unsigned int GRP_HB4HORIZONTALDOORR1	=	65;	//HB4_Horizontal_door_R1
const unsigned int GRP_HB4HORIZONTALDOORL1	=	66;	//HB4_Horizontal_door_L1
const unsigned int GRP_HB4VLD7	=	67;	//HB4_VLD7
const unsigned int GRP_HB4VLD6	=	68;	//HB4_VLD6
const unsigned int GRP_HB4VLD5	=	69;	//HB4_VLD5
const unsigned int GRP_HB4VLD1	=	70;	//HB4_VLD1
const unsigned int GRP_HB2VLD2	=	71;	//HB2_VLD2
const unsigned int GRP_HB2VLD1	=	72;	//HB2_VLD1
const unsigned int GRP_BLOCKJ	=	73;	//block
const unsigned int GRP_GROUP_76	=	74;	//Group 76
const unsigned int GRP_LOWBAYENTRANCE1	=	75;	//LowBay_entrance1
const unsigned int GRP_GROUP_160	=	76;	//Group 160
const unsigned int GRP_GROUP_161	=	77;	//Group 161
const unsigned int GRP_GROUP_162	=	78;	//Group 162
const unsigned int GRP_GROUP_164	=	79;	//Group 164
const unsigned int GRP_GROUP_165	=	80;	//Group 165
const unsigned int GRP_GROUP_166A	=	81;	//Group 166
const unsigned int GRP_GROUP_167	=	82;	//Group 167
const unsigned int GRP_GROUP_169	=	83;	//Group 169
const unsigned int GRP_BLOCKK	=	84;	//block
const unsigned int GRP_BLOCKL	=	85;	//block
const unsigned int GRP_NORTHENTRANCER1	=	86;	//North_entrance_R1
const unsigned int GRP_NORTHENTRANCEL1	=	87;	//North_entrance_L1
const unsigned int GRP_BOXD	=	88;	//box
const unsigned int GRP_VABFLOORB	=	89;	//VAB_floor
const unsigned int GRP_NORTHWINDOW	=	90;	//north_window
const unsigned int GRP_SPHERE	=	91;	//sphere
const unsigned int GRP_SPHEREA	=	92;	//sphere
const unsigned int GRP_SPHEREB	=	93;	//sphere
const unsigned int GRP_SPHEREC	=	94;	//sphere
const unsigned int GRP_SPHERED	=	95;	//sphere
const unsigned int GRP_SPHEREE	=	96;	//sphere
const unsigned int GRP_CYLINDER	=	97;	//cylinder
const unsigned int GRP_CYLINDERA	=	98;	//cylinder
const unsigned int GRP_CYLINDERB	=	99;	//cylinder
const unsigned int GRP_CYLINDERC	=	100;	//cylinder
const unsigned int GRP_CYLINDERD	=	101;	//cylinder
const unsigned int GRP_CYLINDERE	=	102;	//cylinder
const unsigned int GRP_CYLINDERF	=	103;	//cylinder
const unsigned int GRP_CYLINDERG	=	104;	//cylinder
const unsigned int GRP_CYLINDERH	=	105;	//cylinder
const unsigned int GRP_CYLINDERI	=	106;	//cylinder
const unsigned int GRP_CYLINDERJ	=	107;	//cylinder
const unsigned int GRP_CYLINDERK	=	108;	//cylinder
const unsigned int GRP_CYLINDERL	=	109;	//cylinder
const unsigned int GRP_CYLINDERM	=	110;	//cylinder
const unsigned int GRP_CYLINDERN	=	111;	//cylinder
const unsigned int GRP_CYLINDERO	=	112;	//cylinder
const unsigned int GRP_CYLINDERP	=	113;	//cylinder
const unsigned int GRP_CYLINDERQ	=	114;	//cylinder
const unsigned int GRP_CYLINDERR	=	115;	//cylinder
const unsigned int GRP_CYLINDERS	=	116;	//cylinder
const unsigned int GRP_CYLINDERT	=	117;	//cylinder
const unsigned int GRP_CYLINDERU	=	118;	//cylinder
const unsigned int GRP_CYLINDERV	=	119;	//cylinder
const unsigned int GRP_CYLINDERW	=	120;	//cylinder
const unsigned int GRP_CONVEXHULL	=	121;	//convexhull
const unsigned int GRP_CONVEXHULLA	=	122;	//convexhull
const unsigned int GRP_CONVEXHULLB	=	123;	//convexhull
const unsigned int GRP_CONVEXHULLC	=	124;	//convexhull
const unsigned int GRP_CONVEXHULLD	=	125;	//convexhull
const unsigned int GRP_CONVEXHULLE	=	126;	//convexhull
const unsigned int GRP_CONVEXHULLF	=	127;	//convexhull
const unsigned int GRP_CONVEXHULLG	=	128;	//convexhull
const unsigned int GRP_CONVEXHULLH	=	129;	//convexhull
const unsigned int GRP_CONVEXHULLI	=	130;	//convexhull
const unsigned int GRP_CONVEXHULLJ	=	131;	//convexhull
const unsigned int GRP_CONVEXHULLK	=	132;	//convexhull
const unsigned int GRP_BOXE	=	133;	//box
const unsigned int GRP_BOXF	=	134;	//box
const unsigned int GRP_BOXG	=	135;	//box
const unsigned int GRP_BOXH	=	136;	//box
const unsigned int GRP_BOXI	=	137;	//box
const unsigned int GRP_BOXJ	=	138;	//box
const unsigned int GRP_BOXK	=	139;	//box
const unsigned int GRP_BOXL	=	140;	//box
const unsigned int GRP_BOXM	=	141;	//box
const unsigned int GRP_BOXN	=	142;	//box
const unsigned int GRP_BOXO	=	143;	//box
const unsigned int GRP_BOXP	=	144;	//box
const unsigned int GRP_BOXQ	=	145;	//box
const unsigned int GRP_BOXR	=	146;	//box
const unsigned int GRP_BOXS	=	147;	//box
const unsigned int GRP_BOXT	=	148;	//box
const unsigned int GRP_BOXU	=	149;	//box
const unsigned int GRP_BOXV	=	150;	//box
const unsigned int GRP_BOXW	=	151;	//box
const unsigned int GRP_BOXX	=	152;	//box
const unsigned int GRP_BOXY	=	153;	//box
const unsigned int GRP_BOXZ	=	154;	//box
const unsigned int GRP_BOXAB	=	155;	//box
const unsigned int GRP_BOXAC	=	156;	//box
const unsigned int GRP_BOXAD	=	157;	//box
const unsigned int GRP_BOXAE	=	158;	//box

