// ======================================================
// Created by ssumeshc 0.2
// Date of conversion : Sun Mar 30 15:35:45 2014

// Input file: Orbiter.msh
// ======================================================

#pragma once

const unsigned int NUMGRP = 116;

const unsigned int GRP_LEFT_PLBD_EXT	=	0;	//LEFT_PLBD_EXT
const unsigned int GRP_STARBOARD_MIDBODY_AVS_DOOR_7	=	1;	//STARBOARD_MIDBODY_AVS_DOOR_7
const unsigned int GRP_STARBOARD_MIDBODY_AVS_DOOR_4	=	2;	//STARBOARD_MIDBODY_AVS_DOOR_4
const unsigned int GRP_PORT_MIDBODY_AVS_DOOR_7	=	3;	//PORT_MIDBODY_AVS_DOOR_7
const unsigned int GRP_PORT_MIDBODY_AVS_DOOR_4	=	4;	//PORT_MIDBODY_AVS_DOOR_4
const unsigned int GRP_FUSELAGE	=	5;	//FUSELAGE
const unsigned int GRP_VERTICAL_STABILIZER	=	6;	//VERTICAL_STABILIZER
const unsigned int GRP_PLB	=	7;	//PLB
const unsigned int GRP_RIGHT_PLBD_EXT	=	8;	//RIGHT_PLBD_EXT
const unsigned int GRP_AFT_COMPARTMENT_SHOULDERS	=	9;	//AFT_COMPARTMENT_SHOULDERS
const unsigned int GRP_XO576_BULKHEAD	=	10;	//Xo576_BULKHEAD
const unsigned int GRP_XO576_BULKHEAD_EQUIPMENT	=	11;	//Xo576_BULKHEAD_EQUIPMENT
const unsigned int GRP_STBD_PLBD_INTERIOR	=	12;	//STBD_PLBD_INTERIOR
const unsigned int GRP_PORT_PLBD_INTERIOR	=	13;	//PORT_PLBD_INTERIOR
const unsigned int GRP_RIGHT_NLG_DOOR	=	14;	//RIGHT_NLG_DOOR
const unsigned int GRP_PORT_FWD_RADIATOR_COOLANT_LINES	=	15;	//PORT_FWD_RADIATOR_COOLANT_LINES
const unsigned int GRP_STBD_FWD_RADIATOR_COOLANT_LINES	=	16;	//STBD_FWD_RADIATOR_COOLANT_LINES
const unsigned int GRP_LEFT_MLG_DOOR	=	17;	//LEFT_MLG_DOOR
const unsigned int GRP_FUSELAGEA	=	18;	//FUSELAGE
const unsigned int GRP_LEFT_NLG_DOOR	=	19;	//LEFT_NLG_DOOR
const unsigned int GRP_RIGHT_OUTBOARD_ELEVON_SEAL_PANEL	=	20;	//RIGHT_OUTBOARD_ELEVON_SEAL_PANEL
const unsigned int GRP_RIGHT_INBOARD_ELEVON_SEAL_PANEL	=	21;	//RIGHT_INBOARD_ELEVON_SEAL_PANEL
const unsigned int GRP_RIGHT_INBOARD_ELEVON	=	22;	//RIGHT_INBOARD_ELEVON
const unsigned int GRP_RIGHT_OUTBOARD_ELEVON	=	23;	//RIGHT_OUTBOARD_ELEVON
const unsigned int GRP_LEFT_OUTBOARD_ELEVON	=	24;	//LEFT_OUTBOARD_ELEVON
const unsigned int GRP_WATER_COOLANT_LINES	=	25;	//WATER_COOLANT_LINES
const unsigned int GRP_LEFT_INBOARD_ELEVON	=	26;	//LEFT_INBOARD_ELEVON
const unsigned int GRP_XO1307_BULKHEAD	=	27;	//Xo1307_BULKHEAD
const unsigned int GRP_AFT_EVA_WINCH_HANDLE	=	28;	//AFT_EVA_WINCH_HANDLE
const unsigned int GRP_FWD_EVA_WINCH_HOOK	=	29;	//FWD_EVA_WINCH_HOOK
const unsigned int GRP_FWD_EVA_WINCH_HANDLE	=	30;	//FWD_EVA_WINCH_HANDLE
const unsigned int GRP_STBD_PLB_RADIATOR_4	=	31;	//STBD_PLB_RADIATOR_4
const unsigned int GRP_PORT_PLB_RADIATOR_4	=	32;	//PORT_PLB_RADIATOR_4
const unsigned int GRP_STBD_PLB_RADIATOR_1	=	33;	//STBD_PLB_RADIATOR_1
const unsigned int GRP_STBD_PLB_RADIATOR_2	=	34;	//STBD_PLB_RADIATOR_2
const unsigned int GRP_STBD_PLB_RADIATOR_3	=	35;	//STBD_PLB_RADIATOR_3
const unsigned int GRP_PORT_PLB_RADIATOR_1	=	36;	//PORT_PLB_RADIATOR_1
const unsigned int GRP_PORT_PLB_RADIATOR_2	=	37;	//PORT_PLB_RADIATOR_2
const unsigned int GRP_FWD_HOOKS	=	38;	//FWD_HOOKS
const unsigned int GRP_MID_FWD_HOOKS	=	39;	//MID_FWD_HOOKS
const unsigned int GRP_MID_AFT_HOOKS	=	40;	//MID_AFT_HOOKS
const unsigned int GRP_AFT_HOOKS	=	41;	//AFT_HOOKS
const unsigned int GRP_FRCS_MODULE	=	42;	//FRCS_MODULE
const unsigned int GRP_CAM_C	=	43;	//CAM_C
const unsigned int GRP_XO1307_BULKHEADA	=	44;	//Xo1307_BULKHEAD
const unsigned int GRP_WINDOWS	=	45;	//WINDOWS
const unsigned int GRP_ET_DOOR_LEFT	=	46;	//ET_DOOR_LEFT
const unsigned int GRP_ET_DOOR_LEFT_DDM_ARM_AFT	=	47;	//ET_DOOR_LEFT_DDM_ARM_AFT
const unsigned int GRP_ET_DOOR_LEFT_DDM_ARM_FWD	=	48;	//ET_DOOR_LEFT_DDM_ARM_FWD
const unsigned int GRP_ET_DOOR_RIGHT	=	49;	//ET_DOOR_RIGHT
const unsigned int GRP_ET_DOOR_RIGHT_DDM_ARM_AFT	=	50;	//ET_DOOR_RIGHT_DDM_ARM_AFT
const unsigned int GRP_ET_DOOR_RIGHT_DDM_ARM_FWD	=	51;	//ET_DOOR_RIGHT_DDM_ARM_FWD
const unsigned int GRP_STARBOARD_AFT_AVS_DOOR_9	=	52;	//STARBOARD_AFT_AVS_DOOR_9
const unsigned int GRP_STARBOARD_AFT_AVS_DOOR_8	=	53;	//STARBOARD_AFT_AVS_DOOR_8
const unsigned int GRP_PORT_AFT_AVS_DOOR_8	=	54;	//PORT_AFT_AVS_DOOR_8
const unsigned int GRP_PORT_AFT_AVS_DOOR_9	=	55;	//PORT_AFT_AVS_DOOR_9
const unsigned int GRP_STARBOARD_MIDBODY_AVS_DOOR_5	=	56;	//STARBOARD_MIDBODY_AVS_DOOR_5
const unsigned int GRP_STARBOARD_MIDBODY_AVS_DOOR_6	=	57;	//STARBOARD_MIDBODY_AVS_DOOR_6
const unsigned int GRP_STARBOARD_MIDBODY_AVS_DOOR_3	=	58;	//STARBOARD_MIDBODY_AVS_DOOR_3
const unsigned int GRP_PORT_MIDBODY_AVS_DOOR_3	=	59;	//PORT_MIDBODY_AVS_DOOR_3
const unsigned int GRP_PORT_MIDBODY_AVS_DOOR_6	=	60;	//PORT_MIDBODY_AVS_DOOR_6
const unsigned int GRP_PORT_MIDBODY_AVS_DOOR_5	=	61;	//PORT_MIDBODY_AVS_DOOR_5
const unsigned int GRP_STARTRACKERS	=	62;	//STARTRACKERS
const unsigned int GRP_Z_STAR_TRACKER_DOOR	=	63;	//Z_STAR_TRACKER_DOOR
const unsigned int GRP_Y_STAR_TRACKER_DOOR	=	64;	//Y_STAR_TRACKER_DOOR
const unsigned int GRP_ET_DOOR_LEFT_DDM_LINK_ROD_FWD	=	65;	//ET_DOOR_LEFT_DDM_LINK_ROD_FWD
const unsigned int GRP_ET_DOOR_LEFT_DDM_LINK_ROD_AFT	=	66;	//ET_DOOR_LEFT_DDM_LINK_ROD_AFT
const unsigned int GRP_PORTDOOR_PULL	=	67;	//PORTDOOR_PULL
const unsigned int GRP_PORT_CLAMP	=	68;	//PORT_CLAMP
const unsigned int GRP_PORTPUSH_ROD	=	69;	//PORTPUSH_ROD
const unsigned int GRP_NLG_UPPER_TORQUE_ARM	=	70;	//NLG_UPPER_TORQUE_ARM
const unsigned int GRP_NLG_LOWER_TORQUE_ARM	=	71;	//NLG_LOWER_TORQUE_ARM
const unsigned int GRP_NLG_STRUT	=	72;	//NLG_STRUT
const unsigned int GRP_LEFT_MLG_STRUT	=	73;	//LEFT_MLG_STRUT
const unsigned int GRP_RIGHT_ADP	=	74;	//RIGHT_ADP
const unsigned int GRP_SIDE_HATCH_EXTERIOR	=	75;	//SIDE_HATCH_EXTERIOR
const unsigned int GRP_PANTILT_CAM_A	=	76;	//PANTILT_CAM_A
const unsigned int GRP_CAM_A	=	77;	//CAM_A
const unsigned int GRP_CAM_B	=	78;	//CAM_B
const unsigned int GRP_PANTILT_CAM_B	=	79;	//PANTILT_CAM_B
const unsigned int GRP_CAM_D	=	80;	//CAM_D
const unsigned int GRP_PANTILT_CAM_D	=	81;	//PANTILT_CAM_D
const unsigned int GRP_PANTILT_CAM_C	=	82;	//PANTILT_CAM_C
const unsigned int GRP_STBDPUSH_ROD	=	83;	//STBDPUSH_ROD
const unsigned int GRP_STBD_CLAMP	=	84;	//STBD_CLAMP
const unsigned int GRP_STBDDOOR_PULL	=	85;	//STBDDOOR_PULL
const unsigned int GRP_BODYFLAP	=	86;	//BODYFLAP
const unsigned int GRP_LEFT_MLG_SHOCK_STRUT	=	87;	//LEFT_MLG_SHOCK_STRUT
const unsigned int GRP_LEFT_MLG_WHEELS	=	88;	//LEFT_MLG_WHEELS
const unsigned int GRP_CENTER_SSME	=	89;	//CENTER_SSME
const unsigned int GRP_LEFT_SSME	=	90;	//LEFT_SSME
const unsigned int GRP_RIGHT_SSME	=	91;	//RIGHT_SSME
const unsigned int GRP_EVA_THERMAL_COVER	=	92;	//EVA_THERMAL_COVER
const unsigned int GRP_RIGHT_RSB_PANEL	=	93;	//RIGHT_RSB_PANEL
const unsigned int GRP_LEFT_RSB_PANEL	=	94;	//LEFT_RSB_PANEL
const unsigned int GRP_NLG_SHOCK_STRUT	=	95;	//NLG_SHOCK_STRUT
const unsigned int GRP_NLG_WHEELS	=	96;	//NLG_WHEELS
const unsigned int GRP_LEFT_ADP	=	97;	//LEFT_ADP
const unsigned int GRP_ET_DOOR_RIGHT_DDM_LINK_ROD_AFT	=	98;	//ET_DOOR_RIGHT_DDM_LINK_ROD_AFT
const unsigned int GRP_ET_DOOR_RIGHT_DDM_LINK_ROD_FWD	=	99;	//ET_DOOR_RIGHT_DDM_LINK_ROD_FWD
const unsigned int GRP_FWD_FUSELAGE	=	100;	//FWD_FUSELAGE
const unsigned int GRP_TRACKBOX	=	101;	//TRACKBOX
const unsigned int GRP_STARTRACKERSA	=	102;	//STARTRACKERS
const unsigned int GRP_RIGHT_MLG_DOOR	=	103;	//RIGHT_MLG_DOOR
const unsigned int GRP_RIGHT_MLG_STRUT	=	104;	//RIGHT_MLG_STRUT
const unsigned int GRP_RIGHT_MLG_SHOCK_STRUT	=	105;	//RIGHT_MLG_SHOCK_STRUT
const unsigned int GRP_RIGHT_MLG_WHEELS	=	106;	//RIGHT_MLG_WHEELS
const unsigned int GRP_PORT_PLB_RADIATOR_3	=	107;	//PORT_PLB_RADIATOR_3
const unsigned int GRP_LOX_UMBILICAL_PANEL	=	108;	//LOX_UMBILICAL_PANEL
const unsigned int GRP_LH2_UMBILICAL_PANEL	=	109;	//LH2_UMBILICAL_PANEL
const unsigned int GRP_AFT_EVA_WINCH_HOOK	=	110;	//AFT_EVA_WINCH_HOOK
const unsigned int GRP_LEFT_INBOARD_ELEVON_SEAL_PANEL	=	111;	//LEFT_INBOARD_ELEVON_SEAL_PANEL
const unsigned int GRP_LEFT_OUTBOARD_ELEVON_SEAL_PANEL	=	112;	//LEFT_OUTBOARD_ELEVON_SEAL_PANEL
const unsigned int GRP_SSME_HEATSHIELDS	=	113;	//SSME_HEATSHIELDS
const unsigned int GRP_PORT_MIDBODY_AVS_DOOR_4A	=	114;	//PORT_MIDBODY_AVS_DOOR_4
const unsigned int GRP_PORT_MIDBODY_AVS_DOOR_7A	=	115;	//PORT_MIDBODY_AVS_DOOR_7

