#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_SSRMS                               102
#define IDB_BITMAP1                             103
#define IDC_PICTURE1                            1001
#define IDC_HALT                                1003
#define IDC_EPN                                 1020
#define IDC_EPP                                 1021
#define IDC_WRNA                                1022
#define IDC_WRPA                                1023
#define IDC_WYNA                                1024
#define IDC_WYPA                                1025
#define IDC_WPNA                                1026
#define IDC_WPPA                                1027
#define IDC_WPNB                                1028
#define IDC_WPPB                                1029
#define IDC_WYNB                                1030
#define IDC_WYPB                                1031
#define IDC_WRNB                                1032
#define IDC_WRPB                                1033
#define IDC_GRAPPLE                             1035
#define IDC_TRANS_MX                            1042
#define IDC_TRANS_PX                            1043
#define IDC_TRANS_MY                            1044
#define IDC_TRANS_PY                            1045
#define IDC_TRANS_MZ                            1046
#define IDC_TRANS_PZ                            1047
#define IDC_SPEED                               1049
#define IDC_STORE1                              1054
#define IDC_STORE2                              1055
#define IDC_STORE3                              1056
#define IDC_STORE4                              1057
#define IDC_RECALL1                             1059
#define IDC_RECALL4                             1063
#define IDC_RECALL3                             1064
#define IDC_RECALL2                             1065
#define IDC_SEQ                                 1068
#define IDC_SEL                                 1069
#define IDC_LIGHT                               40000
#define GRPPoints                               40001
#define IDC_FRAME                               40002
#define IDC_SHOWGRAPPLE                         40003
#define IDC_ROT_MY                              40004
#define Reference                               40005
#define IDC_ROT_PP                              40006
#define IDC_ROT_PR                              40007
#define IDC_ALL                                 40008
#define IDC_ROT_MP                              40009
#define IDC_ROT_PY                              40010
#define IDC_ROT_MR                              40011
