#ifndef ___GPC_VARIABLE_ALLOCATION_TABLE_H_INCLUDED___
#define ___GPC_VARIABLE_ALLOCATION_TABLE_H_INCLUDED___

#define NUM_GPC_VARIABLES	32768

#define GPCV_OP_CURRENT	0
#define GPCV_OP_NEXT	1
#define GPCV_MET_HIGH	2
#define GPCV_MET_LOW	3
#define GPCV_GMT_HIGH	4
#define GPCV_GMT_LOW	5

#endif