// ======================================================
// Created by ssumeshc 0.2
// Date of conversion : Sun Mar 16 19:30:11 2014

// Input file: Orbiter.msh
// ======================================================

#pragma once

const unsigned int NUMGRP = 111;

const unsigned int GRP_PLB	=	0;	//PLB
const unsigned int GRP_RIGHT_PLBD_EXT	=	1;	//RIGHT_PLBD_EXT
const unsigned int GRP_AFT_COMPARTMENT_SHOULDERS	=	2;	//AFT_COMPARTMENT_SHOULDERS
const unsigned int GRP_XO576_BULKHEAD	=	3;	//Xo576_BULKHEAD
const unsigned int GRP_XO576_BULKHEAD_EQUIPMENT	=	4;	//Xo576_BULKHEAD_EQUIPMENT
const unsigned int GRP_STBD_PLBD_INTERIOR	=	5;	//STBD_PLBD_INTERIOR
const unsigned int GRP_PORT_PLBD_INTERIOR	=	6;	//PORT_PLBD_INTERIOR
const unsigned int GRP_RIGHT_NLG_DOOR	=	7;	//RIGHT_NLG_DOOR
const unsigned int GRP_FUSELAGE	=	8;	//FUSELAGE
const unsigned int GRP_PORT_FWD_RADIATOR_COOLANT_LINES	=	9;	//PORT_FWD_RADIATOR_COOLANT_LINES
const unsigned int GRP_STBD_FWD_RADIATOR_COOLANT_LINES	=	10;	//STBD_FWD_RADIATOR_COOLANT_LINES
const unsigned int GRP_LEFT_MLG_DOOR	=	11;	//LEFT_MLG_DOOR
const unsigned int GRP_FUSELAGEA	=	12;	//FUSELAGE
const unsigned int GRP_LEFT_NLG_DOOR	=	13;	//LEFT_NLG_DOOR
const unsigned int GRP_RIGHT_OUTBOARD_ELEVON_SEAL_PANEL	=	14;	//RIGHT_OUTBOARD_ELEVON_SEAL_PANEL
const unsigned int GRP_RIGHT_INBOARD_ELEVON_SEAL_PANEL	=	15;	//RIGHT_INBOARD_ELEVON_SEAL_PANEL
const unsigned int GRP_RIGHT_INBOARD_ELEVON	=	16;	//RIGHT_INBOARD_ELEVON
const unsigned int GRP_RIGHT_OUTBOARD_ELEVON	=	17;	//RIGHT_OUTBOARD_ELEVON
const unsigned int GRP_LEFT_OUTBOARD_ELEVON	=	18;	//LEFT_OUTBOARD_ELEVON
const unsigned int GRP_WATER_COOLANT_LINES	=	19;	//WATER_COOLANT_LINES
const unsigned int GRP_LEFT_INBOARD_ELEVON	=	20;	//LEFT_INBOARD_ELEVON
const unsigned int GRP_XO1307_BULKHEAD	=	21;	//Xo1307_BULKHEAD
const unsigned int GRP_AFT_EVA_WINCH_HANDLE	=	22;	//AFT_EVA_WINCH_HANDLE
const unsigned int GRP_FWD_EVA_WINCH_HOOK	=	23;	//FWD_EVA_WINCH_HOOK
const unsigned int GRP_FWD_EVA_WINCH_HANDLE	=	24;	//FWD_EVA_WINCH_HANDLE
const unsigned int GRP_LEFT_PLBD_EXT	=	25;	//LEFT_PLBD_EXT
const unsigned int GRP_STBD_PLB_RADIATOR_4	=	26;	//STBD_PLB_RADIATOR_4
const unsigned int GRP_PORT_PLB_RADIATOR_4	=	27;	//PORT_PLB_RADIATOR_4
const unsigned int GRP_STBD_PLB_RADIATOR_1	=	28;	//STBD_PLB_RADIATOR_1
const unsigned int GRP_STBD_PLB_RADIATOR_2	=	29;	//STBD_PLB_RADIATOR_2
const unsigned int GRP_STBD_PLB_RADIATOR_3	=	30;	//STBD_PLB_RADIATOR_3
const unsigned int GRP_PORT_PLB_RADIATOR_1	=	31;	//PORT_PLB_RADIATOR_1
const unsigned int GRP_PORT_PLB_RADIATOR_2	=	32;	//PORT_PLB_RADIATOR_2
const unsigned int GRP_FWD_HOOKS	=	33;	//FWD_HOOKS
const unsigned int GRP_MID_FWD_HOOKS	=	34;	//MID_FWD_HOOKS
const unsigned int GRP_MID_AFT_HOOKS	=	35;	//MID_AFT_HOOKS
const unsigned int GRP_AFT_HOOKS	=	36;	//AFT_HOOKS
const unsigned int GRP_FRCS_MODULE	=	37;	//FRCS_MODULE
const unsigned int GRP_CAM_C	=	38;	//CAM_C
const unsigned int GRP_XO1307_BULKHEADA	=	39;	//Xo1307_BULKHEAD
const unsigned int GRP_WINDOWS	=	40;	//WINDOWS
const unsigned int GRP_ET_DOOR_LEFT	=	41;	//ET_DOOR_LEFT
const unsigned int GRP_ET_DOOR_LEFT_DDM_ARM_AFT	=	42;	//ET_DOOR_LEFT_DDM_ARM_AFT
const unsigned int GRP_ET_DOOR_LEFT_DDM_ARM_FWD	=	43;	//ET_DOOR_LEFT_DDM_ARM_FWD
const unsigned int GRP_ET_DOOR_RIGHT	=	44;	//ET_DOOR_RIGHT
const unsigned int GRP_ET_DOOR_RIGHT_DDM_ARM_AFT	=	45;	//ET_DOOR_RIGHT_DDM_ARM_AFT
const unsigned int GRP_ET_DOOR_RIGHT_DDM_ARM_FWD	=	46;	//ET_DOOR_RIGHT_DDM_ARM_FWD
const unsigned int GRP_STARBOARD_AFT_AVS_DOOR_9	=	47;	//STARBOARD_AFT_AVS_DOOR_9
const unsigned int GRP_STARBOARD_AFT_AVS_DOOR_8	=	48;	//STARBOARD_AFT_AVS_DOOR_8
const unsigned int GRP_PORT_AFT_AVS_DOOR_8	=	49;	//PORT_AFT_AVS_DOOR_8
const unsigned int GRP_PORT_AFT_AVS_DOOR_9	=	50;	//PORT_AFT_AVS_DOOR_9
const unsigned int GRP_MIDBODY_PAYLOAD_UMBILICAL_PANELS	=	51;	//MIDBODY_PAYLOAD_UMBILICAL_PANELS
const unsigned int GRP_STARBOARD_MIDBODY_AVS_DOOR_5	=	52;	//STARBOARD_MIDBODY_AVS_DOOR_5
const unsigned int GRP_STARBOARD_MIDBODY_AVS_DOOR_6	=	53;	//STARBOARD_MIDBODY_AVS_DOOR_6
const unsigned int GRP_STARBOARD_MIDBODY_AVS_DOOR_3	=	54;	//STARBOARD_MIDBODY_AVS_DOOR_3
const unsigned int GRP_PORT_MIDBODY_AVS_DOOR_3	=	55;	//PORT_MIDBODY_AVS_DOOR_3
const unsigned int GRP_PORT_MIDBODY_AVS_DOOR_6	=	56;	//PORT_MIDBODY_AVS_DOOR_6
const unsigned int GRP_PORT_MIDBODY_AVS_DOOR_5	=	57;	//PORT_MIDBODY_AVS_DOOR_5
const unsigned int GRP_STARTRACKERS	=	58;	//STARTRACKERS
const unsigned int GRP_Z_STAR_TRACKER_DOOR	=	59;	//Z_STAR_TRACKER_DOOR
const unsigned int GRP_Y_STAR_TRACKER_DOOR	=	60;	//Y_STAR_TRACKER_DOOR
const unsigned int GRP_ET_DOOR_LEFT_DDM_LINK_ROD_FWD	=	61;	//ET_DOOR_LEFT_DDM_LINK_ROD_FWD
const unsigned int GRP_ET_DOOR_LEFT_DDM_LINK_ROD_AFT	=	62;	//ET_DOOR_LEFT_DDM_LINK_ROD_AFT
const unsigned int GRP_PORTDOOR_PULL	=	63;	//PORTDOOR_PULL
const unsigned int GRP_PORT_CLAMP	=	64;	//PORT_CLAMP
const unsigned int GRP_PORTPUSH_ROD	=	65;	//PORTPUSH_ROD
const unsigned int GRP_VERTICAL_STABILIZER	=	66;	//VERTICAL_STABILIZER
const unsigned int GRP_NLG_UPPER_TORQUE_ARM	=	67;	//NLG_UPPER_TORQUE_ARM
const unsigned int GRP_NLG_LOWER_TORQUE_ARM	=	68;	//NLG_LOWER_TORQUE_ARM
const unsigned int GRP_NLG_STRUT	=	69;	//NLG_STRUT
const unsigned int GRP_LEFT_MLG_STRUT	=	70;	//LEFT_MLG_STRUT
const unsigned int GRP_RIGHT_ADP	=	71;	//RIGHT_ADP
const unsigned int GRP_SIDE_HATCH_EXTERIOR	=	72;	//SIDE_HATCH_EXTERIOR
const unsigned int GRP_PANTILT_CAM_A	=	73;	//PANTILT_CAM_A
const unsigned int GRP_CAM_A	=	74;	//CAM_A
const unsigned int GRP_CAM_B	=	75;	//CAM_B
const unsigned int GRP_PANTILT_CAM_B	=	76;	//PANTILT_CAM_B
const unsigned int GRP_CAM_D	=	77;	//CAM_D
const unsigned int GRP_PANTILT_CAM_D	=	78;	//PANTILT_CAM_D
const unsigned int GRP_PANTILT_CAM_C	=	79;	//PANTILT_CAM_C
const unsigned int GRP_STBDPUSH_ROD	=	80;	//STBDPUSH_ROD
const unsigned int GRP_STBD_CLAMP	=	81;	//STBD_CLAMP
const unsigned int GRP_STBDDOOR_PULL	=	82;	//STBDDOOR_PULL
const unsigned int GRP_BODYFLAP	=	83;	//BODYFLAP
const unsigned int GRP_LEFT_MLG_SHOCK_STRUT	=	84;	//LEFT_MLG_SHOCK_STRUT
const unsigned int GRP_LEFT_MLG_WHEELS	=	85;	//LEFT_MLG_WHEELS
const unsigned int GRP_CENTER_SSME	=	86;	//CENTER_SSME
const unsigned int GRP_LEFT_SSME	=	87;	//LEFT_SSME
const unsigned int GRP_RIGHT_SSME	=	88;	//RIGHT_SSME
const unsigned int GRP_EVA_THERMAL_COVER	=	89;	//EVA_THERMAL_COVER
const unsigned int GRP_RIGHT_RSB_PANEL	=	90;	//RIGHT_RSB_PANEL
const unsigned int GRP_LEFT_RSB_PANEL	=	91;	//LEFT_RSB_PANEL
const unsigned int GRP_NLG_SHOCK_STRUT	=	92;	//NLG_SHOCK_STRUT
const unsigned int GRP_NLG_WHEELS	=	93;	//NLG_WHEELS
const unsigned int GRP_LEFT_ADP	=	94;	//LEFT_ADP
const unsigned int GRP_ET_DOOR_RIGHT_DDM_LINK_ROD_AFT	=	95;	//ET_DOOR_RIGHT_DDM_LINK_ROD_AFT
const unsigned int GRP_ET_DOOR_RIGHT_DDM_LINK_ROD_FWD	=	96;	//ET_DOOR_RIGHT_DDM_LINK_ROD_FWD
const unsigned int GRP_FWD_FUSELAGE	=	97;	//FWD_FUSELAGE
const unsigned int GRP_TRACKBOX	=	98;	//TRACKBOX
const unsigned int GRP_STARTRACKERSA	=	99;	//STARTRACKERS
const unsigned int GRP_RIGHT_MLG_DOOR	=	100;	//RIGHT_MLG_DOOR
const unsigned int GRP_RIGHT_MLG_STRUT	=	101;	//RIGHT_MLG_STRUT
const unsigned int GRP_RIGHT_MLG_SHOCK_STRUT	=	102;	//RIGHT_MLG_SHOCK_STRUT
const unsigned int GRP_RIGHT_MLG_WHEELS	=	103;	//RIGHT_MLG_WHEELS
const unsigned int GRP_PORT_PLB_RADIATOR_3	=	104;	//PORT_PLB_RADIATOR_3
const unsigned int GRP_LOX_UMBILICAL_PANEL	=	105;	//LOX_UMBILICAL_PANEL
const unsigned int GRP_LH2_UMBILICAL_PANEL	=	106;	//LH2_UMBILICAL_PANEL
const unsigned int GRP_AFT_EVA_WINCH_HOOK	=	107;	//AFT_EVA_WINCH_HOOK
const unsigned int GRP_LEFT_INBOARD_ELEVON_SEAL_PANEL	=	108;	//LEFT_INBOARD_ELEVON_SEAL_PANEL
const unsigned int GRP_LEFT_OUTBOARD_ELEVON_SEAL_PANEL	=	109;	//LEFT_OUTBOARD_ELEVON_SEAL_PANEL
const unsigned int GRP_SSME_HEATSHIELDS	=	110;	//SSME_HEATSHIELDS

