// ======================================================
// Created by ssumeshc 0.2
// Date of conversion : Sat May 07 02:50:42 2016

// Input file: CISS_CentaurG_Prime.msh
// ======================================================

#pragma once

const unsigned int NUMGRP_GPRIME = 43;

const unsigned int GRP_AFT_CENTER_GHE_BOTTLES_GPRIME	=	0;	//AFT_CENTER_GHE_BOTTLES
const unsigned int GRP_AFT_GHE_BOTTLES_GPRIME	=	1;	//AFT_GHE_BOTTLES
const unsigned int GRP_CSS_AFT_YOKE_GPRIME	=	2;	//CSS_AFT_YOKE
const unsigned int GRP_DA_ROTATION_ARM_GPRIME	=	3;	//DA_ROTATION_ARM
const unsigned int GRP_DA_ROTATION_LINK_GPRIME	=	4;	//DA_ROTATION_LINK
const unsigned int GRP_GH2_PROPELLANT_DISCONNECT_GPRIME	=	5;	//GH2_PROPELLANT_DISCONNECT
const unsigned int GRP_GOX_PROPELLANT_DISCONNECT_GPRIME	=	6;	//GOX_PROPELLANT_DISCONNECT
const unsigned int GRP_H2_FXIED_DUCTS_GPRIME	=	7;	//H2_FXIED_DUCTS
const unsigned int GRP_LH2_PROPELLANT_DISCONNECT_GPRIME	=	8;	//LH2_PROPELLANT_DISCONNECT
const unsigned int GRP_LOX_PROPELLANT_DISCONNECT_GPRIME	=	9;	//LOX_PROPELLANT_DISCONNECT
const unsigned int GRP_O2_FIXED_DUCTS_GPRIME	=	10;	//O2_FIXED_DUCTS
const unsigned int GRP_AFT_FORWARD_GHE_BOTTLES_GPRIME	=	11;	//AFT_FORWARD_GHE_BOTTLES
const unsigned int GRP_CSS_BULKHEADS_GPRIME	=	12;	//CSS_BULKHEADS
const unsigned int GRP_CSS_FWD_YOKE_GPRIME	=	13;	//CSS_FWD_YOKE
const unsigned int GRP_CSS_KEEL_BEAM_GPRIME	=	14;	//CSS_KEEL_BEAM
const unsigned int GRP_CSS_TRUNNION_KEEL_PINS_GPRIME	=	15;	//CSS_TRUNNION_KEEL_PINS
const unsigned int GRP_FWD_AC_DUCT_GPRIME	=	16;	//FWD_AC_DUCT
const unsigned int GRP_DEPLOYMENT_ADAPTER_GPRIME	=	17;	//DEPLOYMENT_ADAPTER
const unsigned int GRP_GOX_VENT_SEGMENT1_GPRIME	=	18;	//GOX_VENT_SEGMENT1
const unsigned int GRP_GOX_VENT_SEGMENT2_GPRIME	=	19;	//GOX_VENT_SEGMENT2
const unsigned int GRP_GOX_VENT_SEGMENT3_GPRIME	=	20;	//GOX_VENT_SEGMENT3
const unsigned int GRP_LOX_FILL_DRAIN_SEGMENT1_GPRIME	=	21;	//LOX_FILL_DRAIN_SEGMENT1
const unsigned int GRP_LOX_FILL_DRAIN_SEGMENT2_GPRIME	=	22;	//LOX_FILL_DRAIN_SEGMENT2
const unsigned int GRP_LOX_FILL_DRAIN_SEGMENT3_GPRIME	=	23;	//LOX_FILL_DRAIN_SEGMENT3
const unsigned int GRP_GH2_VENT_SEGMENT1_GPRIME	=	24;	//GH2_VENT_SEGMENT1
const unsigned int GRP_GH2_VENT_SEGMENT2_GPRIME	=	25;	//GH2_VENT_SEGMENT2
const unsigned int GRP_GH2_VENT_SEGMENT3_GPRIME	=	26;	//GH2_VENT_SEGMENT3
const unsigned int GRP_LH2_FILL_DRAIN_SEGMENT1_GPRIME	=	27;	//LH2_FILL_DRAIN_SEGMENT1
const unsigned int GRP_LH2_FILL_DRAIN_SEGMENT2_GPRIME	=	28;	//LH2_FILL_DRAIN_SEGMENT2
const unsigned int GRP_LH2_FILL_DRAIN_SEGMENT3_GPRIME	=	29;	//LH2_FILL_DRAIN_SEGMENT3
const unsigned int GRP_PROPELLANT_DISCONNECT_PANELS_GPRIME	=	30;	//PROPELLANT_DISCONNECT_PANELS
const unsigned int GRP_LH2_DUCT_BELLOW3_GPRIME	=	31;	//LH2_DUCT_BELLOW3
const unsigned int GRP_LH2_DUCT_BELLOW2_GPRIME	=	32;	//LH2_DUCT_BELLOW2
const unsigned int GRP_LH2_DUCT_BELLOW1_GPRIME	=	33;	//LH2_DUCT_BELLOW1
const unsigned int GRP_GH2_DUCT_BELLOW3_GPRIME	=	34;	//GH2_DUCT_BELLOW3
const unsigned int GRP_GH2_DUCT_BELLOW2_GPRIME	=	35;	//GH2_DUCT_BELLOW2
const unsigned int GRP_GH2_DUCT_BELLOW1_GPRIME	=	36;	//GH2_DUCT_BELLOW1
const unsigned int GRP_LOX_DUCT_BELLOW2_GPRIME	=	37;	//LOX_DUCT_BELLOW2
const unsigned int GRP_LOX_DUCT_BELLOW3_GPRIME	=	38;	//LOX_DUCT_BELLOW3
const unsigned int GRP_GOX_DUCT_BELLOW3_GPRIME	=	39;	//GOX_DUCT_BELLOW3
const unsigned int GRP_GOX_DUCT_BELLOW2_GPRIME	=	40;	//GOX_DUCT_BELLOW2
const unsigned int GRP_GOX_DUCT_BELLOW1_GPRIME	=	41;	//GOX_DUCT_BELLOW1
const unsigned int GRP_LOX_DUCT_BELLOW1_GPRIME	=	42;	//LOX_DUCT_BELLOW1

