// ======================================================
// Created by ssumeshc 0.1
// Input file: ..\..\..\Meshes\SSU\Crawler_mainbody.msh
// ======================================================

#pragma once

const unsigned int NUMGRP = 167;

const unsigned int GRP_BOX328	=	0;	//Box328
const unsigned int GRP_BOX01	=	1;	//Box01
const unsigned int GRP_BOX02	=	2;	//Box02
const unsigned int GRP_BOX03	=	3;	//Box03
const unsigned int GRP_BOX04	=	4;	//Box04
const unsigned int GRP_BOX05	=	5;	//Box05
const unsigned int GRP_BOX06	=	6;	//Box06
const unsigned int GRP_BOX07	=	7;	//Box07
const unsigned int GRP_BOX08	=	8;	//Box08
const unsigned int GRP_BOX22	=	9;	//Box22
const unsigned int GRP_BOX63	=	10;	//Box63
const unsigned int GRP_BOX75	=	11;	//Box75
const unsigned int GRP_BOX77	=	12;	//Box77
const unsigned int GRP_BOX78	=	13;	//Box78
const unsigned int GRP_BOX82	=	14;	//Box82
const unsigned int GRP_BOX86	=	15;	//Box86
const unsigned int GRP_BOX88	=	16;	//Box88
const unsigned int GRP_BOX101	=	17;	//Box101
const unsigned int GRP_BOX105	=	18;	//Box105
const unsigned int GRP_BOX134	=	19;	//Box134
const unsigned int GRP_BOX186	=	20;	//Box186
const unsigned int GRP_BOX229	=	21;	//Box229
const unsigned int GRP_BOX230	=	22;	//Box230
const unsigned int GRP_BOX239	=	23;	//Box239
const unsigned int GRP_BOX304	=	24;	//Box304
const unsigned int GRP_BOX305	=	25;	//Box305
const unsigned int GRP_BOX324	=	26;	//Box324
const unsigned int GRP_BOX325	=	27;	//Box325
const unsigned int GRP_BOX326	=	28;	//Box326
const unsigned int GRP_BOX327	=	29;	//Box327
const unsigned int GRP_BOX329	=	30;	//Box329
const unsigned int GRP_BOX330	=	31;	//Box330
const unsigned int GRP_BOX331	=	32;	//Box331
const unsigned int GRP_BOX332	=	33;	//Box332
const unsigned int GRP_BOX333	=	34;	//Box333
const unsigned int GRP_BOX334	=	35;	//Box334
const unsigned int GRP_BOX337	=	36;	//Box337
const unsigned int GRP_BOX342	=	37;	//Box342
const unsigned int GRP_BOX343	=	38;	//Box343
const unsigned int GRP_BOX344	=	39;	//Box344
const unsigned int GRP_BOX348	=	40;	//Box348
const unsigned int GRP_BOX349	=	41;	//Box349
const unsigned int GRP_BOX353	=	42;	//Box353
const unsigned int GRP_BOX354	=	43;	//Box354
const unsigned int GRP_BOX532	=	44;	//Box532
const unsigned int GRP_BOX613	=	45;	//Box613
const unsigned int GRP_BOX658	=	46;	//Box658
const unsigned int GRP_BOX713	=	47;	//Box713
const unsigned int GRP_BOX796	=	48;	//Box796
const unsigned int GRP_BOX797	=	49;	//Box797
const unsigned int GRP_BOX798	=	50;	//Box798
const unsigned int GRP_BOX800	=	51;	//Box800
const unsigned int GRP_CAB_1	=	52;	//Cab_1
const unsigned int GRP_CAB_3	=	53;	//Cab_3
const unsigned int GRP_CORNER_A_AUXILLARY_STEERING_ARM	=	54;	//Corner_A_Auxillary_steering_arm
const unsigned int GRP_CORNER_A_FWD_BOTTOM_STEERING_CYLINDER	=	55;	//Corner_A_FWD_bottom_steering_cylinder
const unsigned int GRP_CORNER_A_FWD_BOTTOM_STEERING_CYLINDER_DUST_SHEILD	=	56;	//Corner_A_FWD_bottom_steering_cylinder_dust_sheild
const unsigned int GRP_CORNER_A_FWD_STEERING_CYLINDER	=	57;	//Corner_A_FWD_steering_cylinder
const unsigned int GRP_CORNER_A_FWD_STEERING_CYLINDER_DUST_SHIELD	=	58;	//Corner_A_FWD_steering_cylinder_dust_shield
const unsigned int GRP_CORNER_A_REAR_BOTTOM_STEERING_CYLINDER	=	59;	//Corner_A_Rear_bottom_steering_cylinder
const unsigned int GRP_CORNER_A_REAR_BOTTOM_STEERING_CYLINDER_DUST_SHIELD	=	60;	//Corner_A_Rear_bottom_steering_cylinder_dust_shield
const unsigned int GRP_CORNER_A_REAR_STEERING_CYLINDER	=	61;	//Corner_A_Rear_steering_cylinder
const unsigned int GRP_CORNER_A_REAR_STEERING_CYLINDER_DUST_SHIELD	=	62;	//Corner_A_Rear_steering_cylinder_dust_shield
const unsigned int GRP_CORNER_B_AUXILLARY_STEERING_ARM	=	63;	//Corner_B_Auxillary_steering_arm
const unsigned int GRP_CORNER_B_FWD_BOTTOM_STEERING_CYLINDER	=	64;	//Corner_B_FWD_bottom_steering_cylinder
const unsigned int GRP_CORNER_B_FWD_BOTTOM_STEERING_CYLINDER_DUST_SHIELD	=	65;	//Corner_B_FWD_bottom_steering_cylinder_dust_shield
const unsigned int GRP_CORNER_B_FWD_STEERING_CYLINDER	=	66;	//Corner_B_FWD_steering_cylinder
const unsigned int GRP_CORNER_B_FWD_STEERING_CYLINDER_DUST_SHIELD	=	67;	//Corner_B_FWD_steering_cylinder_dust_shield
const unsigned int GRP_CORNER_B_REAR_BOTTOM_STEERING_CYLINDER	=	68;	//Corner_B_Rear_bottom_steering_cylinder
const unsigned int GRP_CORNER_B_REAR_BOTTOM_STEERING_CYLINDER_DUST_SHEILD	=	69;	//Corner_B_Rear_bottom_steering_cylinder_dust_sheild
const unsigned int GRP_CORNER_B_REAR_STEERING_CYLINDER	=	70;	//Corner_B_Rear_steering_cylinder
const unsigned int GRP_CORNER_B_REAR_STEERING_CYLINDER_DUST_SHIELD	=	71;	//Corner_B_Rear_steering_cylinder_dust_shield
const unsigned int GRP_CORNER_C_AUXILLARY_STEERING_ARM	=	72;	//Corner_C_Auxillary_steering_arm
const unsigned int GRP_CORNER_C_FWD_BOTTOM_STEERING_CYLINDER	=	73;	//Corner_C_FWD_bottom_steering_cylinder
const unsigned int GRP_CORNER_C_FWD_STEERING_CYLINDER	=	74;	//Corner_C_FWD_steering_cylinder
const unsigned int GRP_CORNER_C_FWD_STEERING_CYLINDER_DUST_SHIELD	=	75;	//Corner_C_FWD_steering_cylinder_dust_shield
const unsigned int GRP_CORNER_C_FWD_STEERING_CYLINDER_DUST_SHIELDA	=	76;	//Corner_C_FWD_steering_cylinder_dust_shield
const unsigned int GRP_CORNER_C_REAR_BOTTOM_STEERING_CYLINDER	=	77;	//Corner_C_Rear_bottom_steering_cylinder
const unsigned int GRP_CORNER_C_REAR_STEERING_CYLINDER	=	78;	//Corner_C_Rear_steering_cylinder
const unsigned int GRP_CORNER_D_AUXILLARY_STEERING_ARM	=	79;	//Corner_D_Auxillary_steering_arm
const unsigned int GRP_CORNER_D_FWD_BOTTOM_STEERING_CYLINDER	=	80;	//Corner_D_FWD_bottom_steering_cylinder
const unsigned int GRP_CORNER_D_FWD_BOTTOM_STEERING_CYLINDER_DUST_SHIELD	=	81;	//Corner_D_FWD_bottom_steering_cylinder_dust_shield
const unsigned int GRP_CORNER_D_FWD_STEERING_CYLINDER_DUST_SHIELD	=	82;	//Corner_D_FWD_steering_cylinder_dust_shield
const unsigned int GRP_CORNER_D_REAR_BOTTOM_STEERING_CYLINDER	=	83;	//Corner_D_rear_bottom_steering_cylinder
const unsigned int GRP_CORNER_D_REAR_BOTTOM_STEERING_CYLINDER_DUST_SHIELD	=	84;	//Corner_D_Rear_bottom_steering_cylinder_dust_shield
const unsigned int GRP_CORNER_D_REAR_STEERING_CYLINDER	=	85;	//Corner_D_Rear_steering_cylinder
const unsigned int GRP_CORNER_D_REAR_STEERING_CYLINDER_DUST_SHIELD	=	86;	//Corner_D_Rear_steering_cylinder_dust_shield
const unsigned int GRP_CORNERDC_FWD_STEERING_CYLINDER	=	87;	//CornerDC_FWD_steering_cylinder
const unsigned int GRP_CYLINDER01	=	88;	//Cylinder01
const unsigned int GRP_CYLINDER02	=	89;	//Cylinder02
const unsigned int GRP_CYLINDER10	=	90;	//Cylinder10
const unsigned int GRP_CYLINDER49	=	91;	//Cylinder49
const unsigned int GRP_CYLINDER502	=	92;	//Cylinder502
const unsigned int GRP_CYLINDER506	=	93;	//Cylinder506
const unsigned int GRP_CYLINDER631	=	94;	//Cylinder631
const unsigned int GRP_CYLINDER634	=	95;	//Cylinder634
const unsigned int GRP_CYLINDER635	=	96;	//Cylinder635
const unsigned int GRP_CYLINDER636	=	97;	//Cylinder636
const unsigned int GRP_CYLINDER637	=	98;	//Cylinder637
const unsigned int GRP_CYLINDER638	=	99;	//Cylinder638
const unsigned int GRP_HYDRAULIC_OIL_TANK	=	100;	//Hydraulic_Oil_Tank
const unsigned int GRP_LINE01	=	101;	//Line01
const unsigned int GRP_LINE03	=	102;	//Line03
const unsigned int GRP_LINE10	=	103;	//Line10
const unsigned int GRP_LINE27	=	104;	//Line27
const unsigned int GRP_NASA_LOGO_1	=	105;	//NASA logo 1
const unsigned int GRP_NASA_LOGO_2	=	106;	//NASA logo 2
const unsigned int GRP_NASA_LOGO_3	=	107;	//NASA logo 3
const unsigned int GRP_US_FLAG_1	=	108;	//US flag 1
const unsigned int GRP_US_FLAG_2	=	109;	//US flag 2
const unsigned int GRP_USA_LOGO_1	=	110;	//USA logo 1
const unsigned int GRP_WINDOW_FRAME_01	=	111;	//Window frame 01
const unsigned int GRP_WINDOW_FRAME_02	=	112;	//Window frame 02
const unsigned int GRP_WINDOW_FRAME_03	=	113;	//Window frame 03
const unsigned int GRP_WINDOW_FRAME_04	=	114;	//Window frame 04
const unsigned int GRP_WINDOW_FRAME_05	=	115;	//Window frame 05
const unsigned int GRP_WINDOW_FRAME_06	=	116;	//Window frame 06
const unsigned int GRP_WINDOW_FRAME_07	=	117;	//Window frame 07
const unsigned int GRP_WINDOW_FRAME_08	=	118;	//Window frame 08
const unsigned int GRP_WINDOW_FRAME_09	=	119;	//Window frame 09
const unsigned int GRP_WINDOW_FRAME_10	=	120;	//Window frame 10
const unsigned int GRP_BOX11	=	121;	//Box11
const unsigned int GRP_CYLINDER06	=	122;	//Cylinder06
const unsigned int GRP_BOX09	=	123;	//Box09
const unsigned int GRP_CYLINDER261	=	124;	//Cylinder261
const unsigned int GRP_BOX791	=	125;	//Box791
const unsigned int GRP_BOX30	=	126;	//Box30
const unsigned int GRP_BOX12	=	127;	//Box12
const unsigned int GRP_BOX13	=	128;	//Box13
const unsigned int GRP_BOX15	=	129;	//Box15
const unsigned int GRP_CYLINDER03	=	130;	//Cylinder03
const unsigned int GRP_CYLINDER04	=	131;	//Cylinder04
const unsigned int GRP_CYLINDER05	=	132;	//Cylinder05
const unsigned int GRP_FORWARD_CRANE_HOOK	=	133;	//Forward crane hook
const unsigned int GRP_TUBE01	=	134;	//Tube01
const unsigned int GRP_TUBE02	=	135;	//Tube02
const unsigned int GRP_BOX10	=	136;	//Box10
const unsigned int GRP_FORWARD_CRANE_HOOK01	=	137;	//Forward crane hook01
const unsigned int GRP_CYLINDER639	=	138;	//Cylinder639
const unsigned int GRP_CYLINDER640	=	139;	//Cylinder640
const unsigned int GRP_CYLINDER641	=	140;	//Cylinder641
const unsigned int GRP_BOX809	=	141;	//Box809
const unsigned int GRP_BOX810	=	142;	//Box810
const unsigned int GRP_TUBE03	=	143;	//Tube03
const unsigned int GRP_BOX811	=	144;	//Box811
const unsigned int GRP_CYLINDER642	=	145;	//Cylinder642
const unsigned int GRP_BOX812	=	146;	//Box812
const unsigned int GRP_CYLINDER643	=	147;	//Cylinder643
const unsigned int GRP_BOX813	=	148;	//Box813
const unsigned int GRP_BOX814	=	149;	//Box814
const unsigned int GRP_TUBE04	=	150;	//Tube04
const unsigned int GRP_BOX38	=	151;	//Box38
const unsigned int GRP_BOX39	=	152;	//Box39
const unsigned int GRP_BOX40	=	153;	//Box40
const unsigned int GRP_BOX42	=	154;	//Box42
const unsigned int GRP_BOX46	=	155;	//Box46
const unsigned int GRP_BOX48	=	156;	//Box48
const unsigned int GRP_BOX52	=	157;	//Box52
const unsigned int GRP_BOX53	=	158;	//Box53
const unsigned int GRP_BOX801	=	159;	//Box801
const unsigned int GRP_BOX802	=	160;	//Box802
const unsigned int GRP_BOX803	=	161;	//Box803
const unsigned int GRP_BOX804	=	162;	//Box804
const unsigned int GRP_BOX805	=	163;	//Box805
const unsigned int GRP_BOX806	=	164;	//Box806
const unsigned int GRP_BOX807	=	165;	//Box807
const unsigned int GRP_LINE02	=	166;	//Line02

